spring:
  profiles:
    active: use_message
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    port: 5672

logging:
  level:
    org: error

tutorial:
  client:
    duration: 10000


